"""add is_deleted columns

Revision ID: 6a62e6fb2c2c
Revises: df3a58bb35b9
Create Date: 2026-08-08 21:20:17.818659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a62e6fb2c2c'
down_revision: Union[str, Sequence[str], None] = 'df3a58bb35b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('reviews', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('services', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_deleted')
    op.drop_column('services', 'is_deleted')
    op.drop_column('reviews', 'is_deleted')
    op.drop_column('bookings', 'is_deleted')
    # ### end Alembic commands ###
