"""Rename service_name to name

Revision ID: d23e058613d9
Revises: e0fbfe8e642b
Create Date: 2026-08-06 19:10:32.787853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd23e058613d9'
down_revision: Union[str, Sequence[str], None] = 'e0fbfe8e642b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('services', 'service_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('service_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('services', 'name')
    # ### end Alembic commands ###
