"""Add status and created_at to payments

Revision ID: df3a58bb35b9
Revises: d23e058613d9
Create Date: 2026-08-07 13:13:33.506827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df3a58bb35b9'
down_revision: Union[str, Sequence[str], None] = 'd23e058613d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('status', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'created_at')
    op.drop_column('payments', 'status')
    # ### end Alembic commands ###
