"""add is_deleted to bookings

Revision ID: ee58cdb7d09a
Revises: 6a62e6fb2c2c
Create Date: 2026-08-08 21:35:23.383531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee58cdb7d09a'
down_revision: Union[str, Sequence[str], None] = '6a62e6fb2c2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
